### ISSUE TITLE
PerceptualLoss broken

### ISSUE THREAD

**Issue by rvorias** [minyoungg/pix2latent#1]
https://github.com/richzhang/PerceptualSimilarity was recently updated,
this broke the `import models` that is called from the examples.

```
Traceback (most recent call last):
  File "invert_biggan_adam.py", line 44, in <module>
    loss_fn = LF.ProjectionLoss()
  File "/home/r/.local/share/virtualenvs/single_view_mpi-aYhVwZ1J/lib/python3.6/site-packages/pix2latent/loss_functions.py", line 90, in __init__
    self.ploss_fn = PerceptualLoss(net=lpips_net)
  File "/home/r/.local/share/virtualenvs/single_view_mpi-aYhVwZ1J/lib/python3.6/site-packages/pix2latent/loss_functions.py", line 134, in __init__
    import models
ModuleNotFoundError: No module named 'models'
```

I believe now you should call something like lpips.LPIPS(params) to instantiate a loss object.
(model='net-lin' is also not available anymore)
I'm going to try and clone an older version of the repo.

Update: `git checkout 6abcdd1077b090cb9f0892103b45d56531d50689` seems to do the trick.

**Comment by minyoungg** [comment]
thanks for the heads up.

i updated the codebase to reflect the recent changes to the lpips repo.

`nn.dataparallel` on lpips is broken as of now but will be updated when the lpips repo does a hot fix for this.

closing this for now.
